version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass deV1234 
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
  
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "autorespondez.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/autorespondez'
    ports:
      - '8000:8000'
  
  celery:
    build: .
    command: celery worker -l info -A autorespondez.blueprints.contact.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/autorespondez'

volumes:
  postgres:
  redis:        
